# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

default_platform(:ios)

platform :ios do

  before_all do
    ensure_git_status_clean
    increment_build_number(build_number: number_of_commits)
  end

  desc "Submits a new build to TestFlight"
  lane :test_flight do
    release_build
    upload_ipa_to_testflight
    notification_title = "Kinit v#{get_version_number} (build #{get_build_number}) uploaded to TestFlight"
    slack(
      message: notification_title,
      success: true
    )
    push_me(title: notification_title) if ENV["PUSH_ME_TOKEN"]
  end

  desc "Submits a new build to the App Store"
  lane :app_store do
    release_build
    upload_to_app_store
    notification_title = "Kinit v#{get_version_number} (build #{get_build_number}) uploaded to the AppStore"
    slack(
      message: notification_title,
      success: true
    )
    push_me(title: notification_title) if ENV["PUSH_ME_TOKEN"]
  end

  desc "Builds a release build"
  lane :release_build do |options|
    adhoc = options[:adhoc] ? true : false
    build_type = adhoc ? "adhoc" : "appstore"

    disable_automatic_code_signing
    sync_code_signing(
      git_branch: "kin-ecosystem-F879J8YSJ9",
      username: "fastlane@kinecosystem.com",
      force_for_new_devices: true,
      type: build_type
    )
    build_ios_app(
      scheme: "Kinit",
      export_method: adhoc ? "ad-hoc" : "app-store",
      export_team_id: "F879J8YSJ9"
    )
    notification(
      subtitle: build_type,
      message: "Finished building v#{get_version_number} (build #{get_build_number})"
    )
  end

  desc "Uploads the current (or the latest built) ipa to testflight"
  lane :upload_ipa_to_testflight do
    upload_to_testflight(
      username: "fastlane@kinecosystem.com",
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end

  desc "Builds a release version and distributes (AdHoc) via Beta by Fabric"
  lane :fabric_beta do
    release_build(adhoc: true)
    crashlytics(crashlytics_path: "KinWallet/Crashlytics.framework/")
  end

  after_all do
    git_commit(
      path: [
        "./KinWallet.xcodeproj/project.pbxproj",
        "./KinWallet/Info.plist",
        "./KinWalletTests/Info.plist",
        "./KinWalletUITests/Info.plist",
      ],
      message: "Build number bump"
    )
    enable_automatic_code_signing
  end

  error do |lane, exception, options|
    enable_automatic_code_signing
    notification(
      subtitle: "Error in lane #{lane}",
      message: exception.to_s
    )
  end
end
