# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submits a new build to TestFairy"
  lane :test_fairy do
    ensure_git_status_clean
    build_ios_app(export_method: 'enterprise')
    testfairy(api_key: ENV['testfairy_api_key'],
              auto_update: 'on',
              notify: 'on')
  end
end
